name:                plan-vasalf-net

version:             0.1.1.0
github:              "vasalf/plan-vasalf-net"
license:             BSD3
author:              "Vasily Alferov"
maintainer:          "vasily.v.alferov@gmail.com"
copyright:           "2020-2021 Vasily Alferov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/vasalf/plan-vasalf-net#readme>

dependencies:
- base >= 4.7 && < 5
- yesod >= 1.6
- yesod-auth >= 1.6
- yesod-auth-oauth2 >= 0.6
- yesod-persistent >= 1.6
- persistent-postgresql >= 2.8
- persistent-template >= 2.8
- monad-logger >= 0.3
- text >= 1.2.4
- bytestring >= 0.10
- aeson >= 1.4
- time >= 1.9
- yaml >= 0.11

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  plan-vasalf-net-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - plan-vasalf-net

tests:
  plan-vasalf-net-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - plan-vasalf-net
