postgresConfig:
  postgresHost: localhost
  postgresDbName: plan
  postgresUser: test
  postgresPassword: test
  postgresPort: 5432
googleOAuthSecrets:
  googleClientId: CLIENT_ID
  googleClientSecret: CLIENT_SECRET
